environment:
  nodejs_version: "8"
  COZY_URL:
    secure: b06koRZfV6qLnE8RPcbaiUFIXIA3xc9PkepUZTOnpjAa6LnSKmW3RWCE2CZHSiMs
  COZY_PASSPHRASE:
    secure: 3pxc1SL46fjXrugWO5AtTOyrNKZRka4pSWDDTJOBA3A=
  MOCHA_TIMEOUT: "60000"

install:
  - cmd: appveyor-retry powershell Install-Product node $env:nodejs_version
  - cmd: appveyor-retry yarn
  - cmd: appveyor-retry yarn bootstrap:remote

build: off

test_script:
  - yarn build
  - cmd: yarn test:unit -- --timeout $env:MOCHA_TIMEOUT
  - cmd: yarn test:integration -- --timeout $env:MOCHA_TIMEOUT
  - yarn dist:all

on_failure:
  - node --version
  - npm --version
  - yarn --version
