environment:
  nodejs_version: "6"
  COZY_URL:
    secure: b06koRZfV6qLnE8RPcbaiUFIXIA3xc9PkepUZTOnpjAa6LnSKmW3RWCE2CZHSiMs
  COZY_PASSPHRASE:
    secure: 3pxc1SL46fjXrugWO5AtTOyrNKZRka4pSWDDTJOBA3A=

install:
  - cmd: appveyor-retry powershell Install-Product node $env:nodejs_version
  - cd cli
  - cmd: appveyor-retry yarn
  - cmd: appveyor-retry yarn bootstrap:remote
  - cd ..

build: off

test_script:
  - cd cli
  - yarn build
  - yarn test

on_failure:
  - node --version
  - npm --version
  - yarn --version
